web:
  port: ${PORT} 
services:
  - name: cloudflare alist
    group: core
    url: "https://alist.learnonly.xyz/"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: cloudflare cloud
    url: "https://cloud.learnonly.xyz/"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: cloudflare blog
    url: "https://blog.learnonly.xyz/"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: cloudflare kodbox
    url: "https://kodbox.learnonly.xyz/"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: cloudflare music
    url: "https://music.learnonly.xyz/"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: cloudflare todo
    url: "https://todo.learnonly.xyz/"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: cloudflare v2personal
    url: "https://v2personal.learnonly.xyz/"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
      
