web:
  port: ${PORT} 
services:
  - name: DevOps Project PaaS - Production
    group: core
    url: "https://ing4ecedevops-production.osc-fr1.scalingo.io/"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: DevOps Project PaaS - Staging
    url: "https://ing4ecedevops-staging.osc-fr1.scalingo.io/"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
